[workspace]
authors = ["Thomas Laich <thomaslaich@gmail.com>"]
channels = ["conda-forge"]
name = "nsmithy-minimal"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.5,<3.15"
dotnet = ">=10.0.100,<11"
just = ">=1.51.0,<2"
